[project]
name = "towards-dmri-hipct"
version = "0.1.0"
description = "Analysis code for validating dMRI using HiP-CT as a ground truth reference"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "antspyx>=0.6.3",
    "dask>=2026.3.0",
    "dipy>=1.12.1",
    "fury>=0.12.0",
    "matplotlib>=3.10.9",
    "natsort>=8.4.0",
    "numpy==1.26.4",
    "opencv-python>=4.11.0.86",
    "tqdm>=4.67.3",
    "scikit-learn>=1.5.0",
    "scipy>=1.13.0",
    "zarr==2.18.7",
    "fiberorient>=0.2",
    "setuptools<71",
    "scikit-image>=0.26.0",
    "ome-zarr-models==0.1.10",
    "pydantic-zarr>=0.7",
    "nibabel>=5.4.2",
    "jupyter>=1.1.1",
]
